### ISSUE TITLE
Trying to do custom content in mods and it does not work

### ISSUE THREAD

**Issue by aladairmaxwell** [MasterEric/Kade-Engine#17] opened 2021-09-28 15:59 UTC
Hey so I tried doing a mod in this new ModCore format and I'm trying to add a new character and freeplay song. But in-game I can't attach my character to game's existing songs and if I open Freeplay tab, the game does not respond like this.

![image](https://user-images.githubusercontent.com/69295711/135122899-1dea8ef5-ce5a-43bb-80de-74454e6f529c.png)

It this even possible for doing mods with new content or it's just skin replacements only? I did everything according to guidelines and ENA example as well. Please check this and say where I wrong.

[TestMod.zip](https://github.com/EnigmaEngine/EnigmaEngine/files/7245751/TestMod.zip)

**Comment by EliteMasterEric** [comment] 2021-09-29 02:12
Hey, thank you SO much for taking the time to test out Enigma Engine. It is currently in the early stages of development (my plan is to make an official beta release after I implement the mod menu and custom weeks) but I greatly appreciate the effort you put in to trying to use it now.

Enigma IS designed around adding being able to add completely custom content, not just skin replacements. If you're looking for a better example showcasing custom songs and characters (and not just replacing existing ones) please check out the [Tricky Mod example](https://github.com/EnigmaEngine/ModCore-Tricky-Mod), which is my sandbox environment created with the goal of recreating the Full-Ass Tricky Mod as a togglable mod.

I'd love to help you figure out what's up. Looking at your mod folder, everything seems fine (`shared/images/characters/yellowfireOffsets.txt` is unused but that won't break anything). However, when I open Freeplay, I do get an error related to loading the song file. Due to a change I made in the latest development build, this now appears as a warning in the log file (by the way, there is a log file!) rather than a crash.

I will continue to investigate.

**Conclusion/tl;DR**: Your mod folder looks correct, the problem is with me. Please wait for an update from me or for the v0.2 release of Enigma, coming soon hopefully.

**Comment by EliteMasterEric** [comment] 2021-09-29 07:23
![image](https://user-images.githubusercontent.com/4635334/135221892-15b4eebe-56ca-41ae-9e4d-59ae2a586fa7.png)

Mod loads fine after some fixes. Momentarily, I'll clean up the build and create a `0.2.0-prerelease` for you to test with.

**Comment by aladairmaxwell** [comment] 2021-09-29 08:03
Yes yes, I checked everything and here is what I found out:

1) Song needs `_meta` every time. Without it, Free Mode will not be available. Your Tricky mod is broken too in this way. 
2) Character need some extra lines, such as `"looped": true`. Also I had strange prefixes, I changed them a bit.
3) Character does not need to be written in `characterList` and just be set as .json file name. 

Everything works fine now, I really appreciate for your help and attention. I'm looking forward for custom weeks and stages. ModCore really is a future for FNF modding. 
P.S. Please write some info in [Custom Characters](https://github.com/EnigmaEngine/EnigmaEngine/wiki/Custom-Songs) as soon as you can, it will be really really nice!

**Comment by EliteMasterEric** [comment] 2021-09-29 08:33
> 1. Song needs `_meta` every time. Without it, Free Mode will not be available. Your Tricky mod is broken too in this way.

This will be fixed in the prerelease, the crash bug is now a warning message in the log file.

> 2. Character need some extra lines, such as `"looped": true`. Also I had strange prefixes, I changed them a bit.

`looped` should be an optional attribute but it defaults to false, and I'm not certain right now what circumstances that value is needed in.

> 3. Character does not need to be written in characterList and just be set as .json file name.

Correct.

> Everything works fine now, I really appreciate for your help and attention. I'm looking forward for custom weeks and stages. 

Great to hear!

I'll get around to uploading a compiled build of the `0.2.0-prerelease` version, and add documentation for Custom Characters tomorrow.

**Comment by EliteMasterEric** [comment] 2021-09-30 03:36
@aladairmaxwell Please check out the following build, I tested it with your mod specifically:

https://github.com/EnigmaEngine/EnigmaEngine/releases/tag/v0.2.0-prerelease

Please report any bugs you find to this project (the same way you just did) and remember to include the log file.

**Comment by isakube** [comment] 2021-10-02 16:19
> > 1. Song needs `_meta` every time. Without it, Free Mode will not be available. Your Tricky mod is broken too in this way.
>
> This will be fixed in the prerelease, the crash bug is now a warning message in the log file.

Having no-freeplay songs would be cool as well imo

**Comment by EliteMasterEric** [comment] 2021-10-03 18:12
Once custom week support is added, you'll be able to have songs in Story Mode that don't appear in free play, if you like. Just add them to the custom week then don't add them to `freeplaySonglist.txt`.

**Closed as completed** 2021-11-08 21:32 UTC
Labels: bug
